export const dummyProducts = [
  {
    id: 1,
    title: "Grilled Chicken Pasta",
    description: "Tender grilled chicken served over creamy alfredo pasta with fresh herbs.",
    images: "https://source.unsplash.com/featured/?chicken,pasta",
    category: "Food",
    price: 14.99,
  },
  {
    id: 2,
    title: "Margherita Pizza",
    description: "Classic Italian pizza with fresh mozzarella, tomatoes, and basil.",
    images: "https://source.unsplash.com/featured/?pizza,margherita",
    category: "Food",
    price: 12.5,
  },
  {
    id: 3,
    title: "Cabernet Sauvignon",
    description: "Rich red wine with dark fruit flavors and hints of oak.",
    images: "https://source.unsplash.com/featured/?redwine",
    category: "Wine",
    price: 29.99,
  },
  {
    id: 4,
    title: "Orange Juice",
    description: "Freshly squeezed orange juice packed with vitamin C.",
    images: "https://source.unsplash.com/featured/?orangejuice",
    category: "Juice",
    price: 3.99,
  },
  {
    id: 5,
    title: "Berry Blast Smoothie",
    description: "A refreshing smoothie made with strawberries, blueberries, and yogurt.",
    images: "https://source.unsplash.com/featured/?smoothie,berries",
    category: "Juice",
    price: 5.5,
  },
  {
    id: 6,
    title: "Mojito",
    description: "A classic Cuban cocktail with white rum, mint, and lime.",
    images: "https://source.unsplash.com/featured/?mojito,cocktail",
    category: "Cocktails",
    price: 8.5,
  },
  {
    id: 7,
    title: "Margarita",
    description: "Zesty tequila-based cocktail with lime and orange liqueur.",
    images: "https://source.unsplash.com/featured/?margarita,cocktail",
    category: "Cocktails",
    price: 9.0,
  },
  {
    id: 8,
    title: "Virgin Pina Colada",
    description: "A tropical blend of pineapple and coconut, alcohol-free.",
    images: "https://source.unsplash.com/featured/?pinacolada,mocktail",
    category: "Mocktail",
    price: 6.0,
  },
  {
    id: 9,
    title: "Sparkling Lemonade",
    description: "Refreshing carbonated lemonade with a hint of mint.",
    images: "https://source.unsplash.com/featured/?lemonade,mocktail",
    category: "Mocktail",
    price: 4.5,
  },
  {
    id: 10,
    title: "Cheeseburger Deluxe",
    description: "Juicy beef patty with cheese, lettuce, tomato, and special sauce.",
    images: "https://source.unsplash.com/featured/?burger,cheeseburger",
    category: "Food",
    price: 10.99,
  },
];
