import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFGLWZ2tVLOYB3VyZM9bAnvznsZpyiQWGJoQ&usqp=CAU",
    title: "Chocolate Pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$440,00",
    newPrice: "299",
    type: "Fluffy",
    category: "PAncakes",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXdymweP7JvJ3V9sBFV3JHANgyJPCQ-YpV3g&usqp=CAU",
    title: "Strawberry pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$540,00",
    newPrice: "300",
    type: "Fluffy",
    category: "Pancakes",
  },

  {
    img: "https://olivesnthyme.com/wp-content/uploads/2023/01/Mini-Pancakes-8.jpg",
    title: "Mini Pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$540,00",
    newPrice: "390",
    type: "Basic",
    category: "Pancakes",
  },
  {
    img: "https://www.ambitiouskitchen.com/wp-content/uploads/2019/04/bananaoatmealpancakes-6-725x725-1.jpg",
    title: "Banana Oatmeal",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$340,00",
    newPrice: "300",
    type: "Creamy",
    category: "Pancakes",
  },
  {
    img: "https://cdn.loveandlemons.com/wp-content/uploads/2022/09/oatmeal-pancakes.jpg",
    title: "Oatmeal pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$340,00",
    newPrice: "250",
    type: "Creamy",
    category: "Pancakes",
  },
  {
    img: "https://wearenotmartha.com/wp-content/uploads/mm-pancakes-featured.jpg",
    title: "M&M pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$440,00",
    newPrice: "250",
    type: "Fluffy",
    category: "Pancakes",
  },

  {
    img: "https://www.wholesomeyum.com/wp-content/uploads/2017/03/wholesomeyum-Low-Carb-Keto-Pancakes-Recipe-21-500x500.jpg",
    title: "Keto fluffy pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$440,00",
    newPrice: "250",
    type: "Creamy",
    category: "Pancakes",
  },

  {
    img: "https://joyfoodsunshine.com/wp-content/uploads/2022/08/chocolate-chip-pancakes-1.jpg",
    title: "Chocolate chip pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$340,00",
    newPrice: "299",
    type: "Creamy",
    category: "Pancakes",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwlIreayksfVp7BuFdVFB4SerOdnE7RS3zAQ&usqp=CAU",
    title: "White Russian",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    type: "Drink",
    color: "blue",
    category: "Cocktails",
  },

  {
    img: "https://vegarecepten.com/wp-content/uploads/2020/05/Regenboog-paradise-cocktail-met-blue-curacao.jpg",
    title: "Rainbow Paradise",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$240,00",
    newPrice: "150",
    type: "Drink",
    category: "Cocktails",
  },
  {
    img: "https://assets.bonappetit.com/photos/650df690c94ec4218673b45a/1:1/w_2560%2Cc_limit/20230915-WEB-SEO-0882_update%2520copy.jpg",
    title: "cosmopolitan cocktail",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$340,00",
    newPrice: "150",
    type: "Drink",
    category: "Cocktails",
  },
  {
    img: "https://images.immediate.co.uk/production/volatile/sites/2/2022/09/Purple-rain-90edf70.jpg?quality=90&resize=556,505",
    title: "Purple rain",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$340,00",
    newPrice: "250",
    type: "Drink",
    category: "Cocktails",
  },
  {
    img: "https://assets.epicurious.com/photos/5601743abd6b8b837d72d526/1:1/w_2560%2Cc_limit/51147000_mint-chocolate-chip-pancakes.jpg",
    title: "Mint choco pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$440,00",
    newPrice: "299",
    type: "Fluffy",
    category: "Pancakes",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTjaDp3sd8MzcQBBbunGGVBLFico5-H_o38w&usqp=CAU",
    title: "buttermilk pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$340,00",
    newPrice: "250",
    type: "Creamy",
    category: "Pancakes",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBI2wqb1tLKL7O1ZWcoUNsZKPYF3AvtGL63Q&usqp=CAU",
    title: "Fluffy pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$340,00",
    newPrice: "199",
    type: "Fluffy",
    category: "Pancakes",
  },
  {
    img: "https://iowagirleats.com/wp-content/uploads/2020/04/Perfect-Gluten-Free-Pancakes-NEW-iowagirleats-Featured.jpg",
    title: "Gluten free pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    type: "Fluffy",
    category: "Pancakes",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2vbmen2YA7GGGRns_7sLzgJ-3-X_dipaHTg&usqp=CAU",
    title: "Rose-Mary wine",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$540,00",
    newPrice: "300",
    type: "Drink",
    category: "Wine",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOc04Flr63K4-YidkXMCZLGGjznSXnEHEYQg&usqp=CAU",
    title: "Colio wine",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$240,00",
    newPrice: "180",
    type: "Drink",
    category: "Wine",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRHZHc7Ve-ceNNl0_ozK4WLZooeYRp8lP0Xw&usqp=CAU",
    title: "Organic wine",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$840,00",
    newPrice: "300",
    type: "Drink",
    category: "Wine",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Z7XfXojML.jpg",
    title: "Jost wine",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    type: "Drink",
    category: "Wine",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ5-ypQd0XWE6vK5iz6Kx8bHBuJk_FVGlB-A&usqp=CAU",
    title: "Fluffy protein pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$540,00",
    newPrice: "300",
    type: "Basic",
    category: "Pancakes",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7Pk5xdDN43M-wETRcxm6cb_ptEkhwJ4NM9w&usqp=CAU",
    title: "Easy Cinnamon pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$440,00",
    newPrice: "150",
    type: "Fluffy",
    category: "Pancakes",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsmQGa29NqXQryq4gk19HE2z_K1s9rwCldxw&usqp=CAU",
    title: "Lemon pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$340,00",
    newPrice: "200",
    type: "Basic",
    category: "Pancakes",
  },

  {
    img: "https://sugargeekshow.com/wp-content/uploads/2020/05/sourdough-discard-pancakes-11-1.jpg",
    title: "Sourdough pancakes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$300,00",
    newPrice: "200",
    type: "Basic",
    category: "Pancakes",
  },
  {
    img: "https://artfultea.com/cdn/shop/articles/BC_2B-_2BAssam_2B_28cup_29_2B_281055_29.jpg?v=1664455870&width=1920",
    title: "Loose leaf tea",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$130,00",
    newPrice: "90",
    type: "Drink",
    category: "Tea",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-XuuQp0r8kiERMTfFadt65fsdcJOiYdC_Tg&usqp=CAU",
    title: "Havard tea",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$190,00",
    newPrice: "100",
    type: "Drink",
    category: "Tea",
  },
  {
    img: "https://www.sharmispassions.com/wp-content/uploads/2011/04/GREENTEA5-500x500.jpg",
    title: "Lemon tea",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "80",
    type: "Drink",
    category: "Tea",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQktjM4_br8zXYUzTLKNkgAqePkn_7vtDGRww&usqp=CAU",
    title: "Green tea",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$150,00",
    newPrice: "70",
    type: "Drink",
    category: "Tea",
  },
];

export default data;